version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: food_ordering_app
    ports:
      - "5433:5432" # expose Postgres to host on port 5433
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # backend exposed to host
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres   # important: docker service name
      - DB_PORT=5432
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # frontend exposed to host
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000/rpc # docker service name
      - VITE_WS_URL=ws://backend:8000/ws     # docker service name
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  db_data:
